project:
  type: book

book:
  title: |
    STA 2300 Intro to Data Science
  sidebar:
    style: "docked"
    search: true
    title: " "
    background: "#154734"
    foreground: "#FFB81c"
  # page-footer: 
  #   left: |
  #     STA 2381
  reader-mode: true
  page-navigation: false
  
  chapters:
    - index.qmd
    - 01.qmd
    - 02.qmd
    - 03.qmd
    - 04.qmd
    - 05.qmd
    - 06.qmd
    - 07.qmd
    - 08.qmd
    - 09.qmd
    - 10.qmd
    - 11.qmd
    - 12.qmd
    - 13.qmd
    - 14.qmd
    - 15.qmd
    - 16.qmd
    - 17.qmd
    - 18.qmd
    - 19.qmd
    - 20.qmd
    - 21.qmd
    - 22.qmd


execute: 
  warning: false
  message: false
  freeze: auto

format:
  html:
    theme: cosmo
    code-link: true
    fig-width: 6
    fig-height: 3
    number-sections: true
    number-depth: 1
    include-in-header:
      text: |
        <style type="text/css">
        .sidebar .chapter-number {
        color: #FFB81c;
        }
        freeblank {
          color: transparent;
          cursor: pointer;
        }
        freeblank.clicked {
          color: red;
        }
        blank {
          display: inline-block; 
          position: relative;
          padding: 0 10px;
          color: transparent;
          cursor: pointer;
        }
        blank::before {
          content: ''; /* Creates a custom underline */
          position: absolute;
          left: 0;
          right: 0;
          bottom: 0;
          height: 1px; /* Thickness of the underline */
          background-color: black; /* Color of the underline */
        }
        blank.clicked {
          color: red;
        }
        </style>
        <script>
        document.addEventListener('click', (event) => {
          if (event.target.tagName === 'BLANK') {
            event.target.classList.add('clicked');
          }
        });
        document.addEventListener('click', (event) => {
          if (event.target.tagName === 'FREEBLANK') {
            event.target.classList.add('clicked');
          }
        });
        </script>
  # pdf:
  #   documentclass: book
  #   number-depth: 3
  #   keep-tex: true
  #   output-file: index.pdf

custom-callout:
  example:
    title: "Example"
    icon-symbol: "📈"
    appearance: "simple"
    color: "#008000"
filters:
- custom-callout

editor: visual
